Revisats scripts i afegides funcionalitats
S'han revisat els scripts, i també s'han afegit noves funcionalitats.

diff --git a/ac_crear_acA b/ac_crear_acA
--- a/ac_crear_acA
+++ b/ac_crear_acA
@@ -3,7 +3,13 @@
 # Construir CSR per al certificat de l'AC Arrel
 openssl req -new -config acA.conf -out ac/acA.csr -keyout ac/acA/private/acA.key
 
-# Crear certificat de l'AC Arrel
-openssl ca -selfsign -config acA.conf -in ac/acA.csr -out ac/acA.crt -extensions acA_ext
-
-echo "ac_crear_aCA finalitzat. Si heu creat correctament el certificat acA, podeu procedir a crear el certificat AC Intermèdia amb 'ac_crear_acI'"
+if [ $? -eq 0 ]; then
+   # Crear certificat autosignat de l'AC Arrel
+   openssl ca -selfsign -config acA.conf -in ac/acA.csr -out ac/acA.crt -extensions acA_ext
+   
+   if [ $? -eq 0 ]; then
+      echo "ac_crear_aCA finalitzat. Podeu procedir a crear el certificat AC Intermèdia amb 'ac_crear_acI'"
+   fi
+else
+   echo "Error! No ha estat possible crear el certificat de l'AC Arrel."
+fi
diff --git a/ac_crear_acI b/ac_crear_acI
--- a/ac_crear_acI
+++ b/ac_crear_acI
@@ -1,7 +1,16 @@
 #!/bin/bash
 
-# Construir CSR per al certificat AC Intermediària
+# Construir CSR per al certificat AC Intermèdia
 openssl req -new -config acI.conf -out ac/acI.csr -keyout ac/acI/private/acI.key
 
-# Crear el certificat per l'AC Intermediària
-openssl ca -config acA.conf -in ac/acI.csr -out ac/acI.crt -extensions acI_ext
+if [ $? -eq 0 ]; then
+   # Crear el certificat per l'AC Intermèdia
+   openssl ca -config acA.conf -in ac/acI.csr -out ac/acI.crt -extensions acI_ext
+
+   if [ $? -eq 0 ]; then
+      echo "ac_crear_aCI finalitzat. Podeu procedir a construir la cadena de certificació amb 'ac_crear_cacert'."
+   fi
+else
+   echo "Error! No ha estat possible crear el certificat de l'AC Intermèdia."
+fi
+
